version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todo_db
    restart: always
    env_file:
      - ./.env.db      
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: todo_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"

volumes:
  db_data:
